TRAIN:
  ENABLE: True
  DATASET: videoabc
  BATCH_SIZE: 36
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
VIDEOABC:
  ENABLE: True
  USE_INTRA: True
  USE_EMBED: True
  SLOW_ONLY: False
DATA:
  NUM_FRAMES: 72
  CLIP_LEN: 8
  METADATA: metadata
  SETTING: long6
  MAX_LENGTH: 7
  PATH_TO_DATA_DIR: data
  INPUT_CHANNEL_NUM: [3, 3]
  TRAIN_CROP_SIZE: 112
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 2
SOLVER:
  BASE_LR: 0.03
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  ARCH: slowfast
  MODEL_NAME: resnet34_2d3d_full
  LOSS_FUNC: videoabc_reason_loss
  DROPOUT_RATE: 0.0
  HEAD_ACT: identity
TEST:
  ENABLE: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  LOG_DIR: tb
NUM_GPUS: 2
LOG_MODEL_INFO: False
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: train_log/VideoABC_DPC
